ALTER TABLE encoded MODIFY COLUMN decisionMaker VARCHAR(255) DEFAULT NULL;
ALTER TABLE encoded MODIFY COLUMN dmDesignation VARCHAR(255) DEFAULT NULL;
ALTER TABLE encoded MODIFY COLUMN existingSystem VARCHAR(255) DEFAULT NULL;
